config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "/about" => "home#about"
  get "home" => "home#index"
  devise_for :users
  resources :users
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
	validates :body, length: { maximum: 200}

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:user_id]

  attachment :image

  has_many :books, dependent: :destroy

  validates :name, presence: true
  validates :name, length:{minimum: 2}
  validates :name, length:{maximum: 20}
  validates :introduction, length:{maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		user_path(current_user)
	end

	def after_sign_out_path_for(resource)
		root_path
	end

	protected

	def configure_permitted_parameters
	  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
	  	devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :introduction,:profile_image])
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!,only:[:index,:new,:show]

  def index
  	@book = Book.new
  	@Books = Book.all
    @User = current_user
  end

  def show
    @bookdetail = Book.find(params[:id])
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def new
    @Books = Book.new
  end

  def create
  	@book = current_user.books.build(book_params)
    if @book.save
      redirect_to book_path(@book)
    else
      @Books = Book.all
      render "index"
    end

  end

  def update
    user = Book.find(params[:id])
    user.update(book_params)
    redirect_to book_path(user)
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to books_path
  end

   private
    def book_params
      params.require(:book).permit(:title, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@Books = Book.new
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!,only:[:index,:new,:show]

  def new
    @Books = Book.new
  end

  def index
  	@book = Book.new
  	@books = Book.all
    @User = current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to books_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id)
    flash[:success] = "successfully"
    else
      render :action => "edit"
    end
  end

  def top

  end

  private

  def user_params
  	params.require(:user).permit(:name, :image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="page-header"></div>

<div class="body" >
  <div class="container">
    <p id="notice"></p>
    <div class="row">
    <div class="col-md-6 col-md-offset-3">
<h2>Editing book</h2>

<% if @book.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for(@book) do |f| %>
    <div class="field row">
    <label for="title">Title</label><br>
    <%= f.text_field :title, class: "col-xs-12" %>
    </div>
    <div class="field row">
    <label for="Opinion">Opinion</label><br>
    <%= f.text_area :body, class: "col-xs-12" %>
    </div>

    <div class="action row"><%= f.submit 'Update book', class:" btn btn-primary col-xs-12"%></div>
    <div class="col-md-3"></div>

<% end %>

    <%= link_to"Show", book_path(@book.id) %>
    |
    <%= link_to"Back", books_path %>
</div>
</div>
</div>
</div>

app/views/books/index.html.erb
<div class="body" >
  <div class="container">
    <p id="notice"></p>
    <div class="row">
  <% if @book.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="col-xs-3">
  <%= render "users/userinfo" %>
</div>

    <div class="col-xs-9">
<h2>Books</h2>
  <table class="table table-hover table-inverse">
  	<thead>
  	  <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
       </tr>
    </thead>
    <tbody>
        <% @Books.each do |book| %>
        <tr>
          <td class="image"><%= attachment_image_tag book.user, :image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" , class: "img" %></td>
      		<td class="title"><%= link_to book.title, book_path(book.id) %></td>
      		<td class="Body"><%= book.body %></td>
        </tr>
        <% end %>
    </tbody>
  </table>
  </div>
  </div>
  </div>
</div>

app/views/books/new.html.erb
<section class="slice sct-color-1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">

        <div class="row">
          <div class="col-md-6 col-md-offset-3 post_image_form">
            <div class="section-title-wrapper style-1 v1">
              <h3 class="section-title section-title-sm left">
                <span>画像投稿フォーム</span>
              </h3>
            </div>

            <%= form_for(@Books, url: books_path) do |f| %>
            <% if @Books.errors.any? %>
              <div id="error_explanation">
                <h2><%= @books.errors.count %>件のエラーが発生しました。</h2>
                <ul>
                <% @Books.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="row">
              <div class="col-sm-12">
              </div>
            </div>
            <br>
            <div class="row">
              <div class="col-sm-6">
                <div class="form-group has-icon">
                  <label class="control-label sr-only">book</label>
                  <%= f.text_field :book_name, class:"form-control", placeholder:"book" %>
                  <span class="fa fa-building form-control-icon" aria-hidden="true"></span>
                </div>
              </div>
              <div class="col-sm-6">
              </div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
              </div>
            </div>
            <hr>
            <%= f.submit "送信", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/books/show.html.erb
<div class="page-header"></div>

<div class="body" >
  <div class="container">
    <p id="notice"></p>
    <div class="row">
      <div class="col-xs-3">
  <h2>User info</h2>
        <%= attachment_image_tag @bookdetail.user, :image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" ,:size => "40x40" %>

      <table class="table" style="table-layout:fixed;width:100%;">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @bookdetail.user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th style="word-wrap:break-word;"><%=@bookdetail.user.introduction %></th>
          </tr>
        </tbody>
    </table>
    <div class="row"><%= link_to"", edit_user_path(@bookdetail.user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench"  %></div>

    <%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>

  <h2>New Book</h2>
    <%= form_for(@book) do |f| %>
    <div class="field row">
      <label>Title</label><br>
      <%= f.text_field :title, class:"col-xs-12" %>
    </div>

    <div class="field row">
      <label>Body</label><br>
      <%= f.text_area :body, class:"col-xs-12" %>
    </div>
    <br>
    <div class="actions row"><%= f.submit 'Create Book', class:" btn btn-primary col-xs-12" %></div>

<% end %>
</div>

    <div class="col-xs-9">
<h2>Book detail</h2>
<table class="table" style="table-layout:fixed;width:100%;">
    <thead></thead>
    <tbody>
      <tr>
        <td class="image"><%= attachment_image_tag @bookdetail.user, :image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" ,:size => "40x40" %>
         <br>
         <%= link_to @bookdetail.user.name, user_path(@bookdetail.user) %>
        </td>
        <td class="title"><%= link_to @bookdetail.title, book_path(@bookdetail) %></td>
        <td class="body" style="word-wrap:break-word;" ><%= @bookdetail.body %></td>
        <td>
        <%if @bookdetail.user == current_user %>
        <%= link_to"Edit", edit_book_path(@bookdetail), class:"btn-sm btn-success" %>
        </td>
        <td>
        <%= link_to"Destroy", book_path(@bookdetail.id), method: :delete, "data-confirm" =>"Are you sure?", class:"btn-sm btn-danger" %>
        <% end %>
        </td>
      </tr>

    </tbody>
</table>
</div>
</div>
</div>
</div>

app/views/home/about.html.erb
<div class="container">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
    	<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight Infratop.inc</p>
    	</div>

app/views/home/index.html.erb
<div class="container">

        <p id="notice"></p>

      	<div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
    <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
          <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
          <p>you can share and exchange  your opinions , inpressions , and emotions</p>
          <p> about varioius books!</p>

    <div class="btn-wrapper">
      <div class="row">
         <p>
          <a class="btn btn-info col-xs-10 col-xs-offset-1" href="/users/sign_in">Log in</a>
        </p>
      </div>
      <div class="row">
        <p><a class="btn btn-success col-xs-10 col-xs-offset-1" href="/users/sign_up">Sign Up</a></p>
      </div>
    </div>

  </div>
</div>

      </div>
    </div>

    <footer>
  <div class="container">
  	<div class="row">
    	<div class="col-xs-3 col-xs-offset-9">
    		<p>CopyRight Infratop.inc</p>
    	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <!--   <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>  -->
     <header>
      <div class="container">
      <div class="header-left">
        <h4>Bookers</h4>
      </div>

    <div class="header-right">
      <% if user_signed_in? %>
        <ul>
          <li>
            <%=link_to "Home", user_path(current_user) %>
          </li>
          <li>
            <%=link_to "Users", users_path %>

          </li>
          <li>
            <%=link_to "Books", books_path %>

          </li>
          <li>
            <%=link_to "Logout", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
        <% else %>
          <ul>
          <li>
            <%=link_to "Home", root_path %>
          </li>
          <li>
             <%=link_to "About",  "/about"%>
          </li>
          <li>
            <%=link_to "sign up",  new_user_registration_path %> 
          </li>
          <li>
            <%=link_to "login",  new_user_session_path %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
  </header>
    <%= yield %>
  </body>
</html>

app/views/users/_userinfo.html.erb
<h2>User info</h2>
        <%= attachment_image_tag current_user, :image,:fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg",  class: "img-info" ,:size => "40x40" %>

      <table class="table" style="table-layout:fixed;width:100%;">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= current_user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th style="word-wrap:break-word;"><%= current_user.introduction %></th>
          </tr>
        </tbody>
    </table>
    <div class="row"><%= link_to"", edit_user_path(current_user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench"  %></div>


  <h2>New Books</h2>
    <%= form_for(Book.new) do |f| %>
    <div class="field row">
      <label>Title</label><br>
      <%= f.text_field :title, class:"col-xs-12" %>
    </div>

    <div class="field row">
      <label>Body</label><br>
      <%= f.text_area :body, class:"col-xs-12" %>
    </div>
    <br>
    <div class="actions row"><%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %></div>

<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

 <%= form_for (@user) do |f| %>

 	<div class="field">
 		<%= f.label :Name %>
 		<%= f.text_field :name %>
 		<%= f.label :Image %>
 		<%= f.attachment_field :image %>
 		<%= f.label :Introduction %>
 		<%= f.text_area :introduction %>
 		<%= f.submit "Update User" %>
 	</div>

<% end %>

app/views/users/index.html.erb
<div class="page-header"></div>

<div class="body" >
  <div class="container">
    <p id="notice"></p>
    <div class="row">
  <div class="col-xs-3">
  <%= render "users/userinfo" %>
</div>


    <div class="col-xs-9">
    <h2>Users</h2>

  <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td class="img"><%= attachment_image_tag book.user, :image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", class: "img" %>
                </td>
          <td class="user-name"><%= book.user.name %></td>
          <td><%= link_to"Show", user_path(book.user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
    </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="page-header"></div>

<div class="body" >
  <div class="container">
    <p id="notice"></p>
    <div class="row">
  <div class="col-xs-3">
  <%= render "users/userinfo" %>
</div>


    <div class="col-xs-9">
    <h2>Books</h2>

  <table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
    <tbody>
      <% @book.each do |book| %>
        <tr>
          <td class="img"><%= attachment_image_tag book.user, :image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", class: "img" %>
                </td>
          <td class="user-name"><%= book.user.name %></td>
          <td><%= link_to"Show", user_path(book.user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
    </div>
    </div>
  </div>
</div>